"""empty message

Revision ID: 00576c996e08
Revises: dc0225f11987
Create Date: 2021-01-03 17:12:35.515245

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '00576c996e08'
down_revision = 'dc0225f11987'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Actors')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Actors',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Actors_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('age', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('gender', postgresql.ENUM('one', 'two', 'three', name='genderenum'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Actors_pkey')
    )
    # ### end Alembic commands ###
